name: LodServerSupport
version: '${version}'
main: dev.vox.lss.paper.LSSPaperPlugin
api-version: '1.21'
description: Paper Plugin that provides unofficial multiplayer support for Voxy.
author: VoX
website: https://modrinth.com/plugin/lod-server-support
commands:
  lsslod:
    description: LOD Server Support admin commands
    usage: /lsslod <stats|diag>
    permission: lss.admin
permissions:
  lss.admin:
    description: Access to LSS admin commands
    default: op
